# Generated by Django 4.1.1 on 2022-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.CharField(choices=[('CC', 'Credit Card'), ('CQ', 'Chequing')], default='CC', max_length=2)),
                ('category', models.CharField(choices=[('RT', 'Rent'), ('GC', 'Groceries')], default=None, max_length=2)),
                ('Notes', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
