# Generated by Django 4.1.1 on 2022-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxn',
            old_name='Notes',
            new_name='notes',
        ),
    ]
