# Generated by Django 4.1 on 2022-11-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_alter_trxn_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxn',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'accType': ['Asset', 'Liability', 'Equity']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
