# Generated by Django 4.1 on 2023-01-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_budget_account_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxn',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trxn',
            name='category',
        ),
        migrations.AddField(
            model_name='trxn',
            name='fromAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromAccount', to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxn',
            name='toAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toAccount', to='api.account'),
            preserve_default=False,
        ),
    ]
