# Generated by Django 4.1 on 2023-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trxn_account_remove_trxn_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Own', 'Own'), ('Flow', 'Flow'), ('Save', 'Save'), ('Equity', 'Equity')], max_length=10),
        ),
    ]
